wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1670444495.212989
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.7.13
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
arch:
  desc: null
  value:
    args:
      class_num: 10
      dropout: 0.2
      embed_dim: 128
      hidden_dim: 64
      nhead: 4
      nhid: 16
      nlayers: 2
      skill_embed_dim: 128
      skill_num: 11721
    type: Skill_Evolve_Hetero
data_loader:
  desc: null
  value:
    args:
      batch_size: 1024
      data_dir: ./data/skill_inflow_outflow/
      graph_dir: ./data/myGraph.gpickle
      max_length: 18
      num_workers: 2
      shuffle: true
      skill_num: 11721
      validation_split: 0.16
    type: SkillDataLoader
device_id:
  desc: null
  value: 1
hparam:
  desc: null
  value:
    class_num: 10
loss:
  desc: null
  value: nll_loss
lr_scheduler:
  desc: null
  value:
    args:
      gamma: 0.1
      step_size: 50
    type: StepLR
metrics:
  desc: null
  value:
  - accuracy_metric
  - f1_metric
  - aucroc_metric
n_gpu:
  desc: null
  value: 1
name:
  desc: null
  value: Skill_Evolve_Hetero-3
optimizer:
  desc: null
  value:
    args:
      amsgrad: true
      lr: 0.001
      weight_decay: 0
    type: Adam
trainer:
  desc: null
  value:
    early_stop: 10
    epochs: 100
    monitor: min val_loss
    save_dir: saved/
    save_period: 10
    tensorboard: true
    verbosity: 2
